#!/usr/bin/env php
<?php declare(strict_types=1);
/**
 * Part of cross-env project.
 *
 * @copyright  Copyright (C) 2019 ${ORGANIZATION}.
 * @license    MIT
 */

use CrossEnv\CrossEnv;

$autoload = __DIR__ . '/vendor/autoload.php';

if (!is_file($autoload)) {
    $autoload = __DIR__ . '/../../autoload.php';
}

require $autoload;

ini_set('memory_limit', '-1');
ini_set('max_execution_time', '0');

exit((new CrossEnv())->run($_SERVER['argv']));
